name: face_camera_controller
description: Upgrade your Flutter camera app with seamless face detection. This camera controller simplifies real-time face recognition integration for an enhanced user experience.
version: 0.0.6
repository: https://github.com/amir1430/face-camera-controller

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.9.0
  google_mlkit_face_detection: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
