name: face_camera_controller
description: Flutter camera controller with face detection ability.
version: 0.0.1
repository: https://github.com/amir1430/face-camera-controller

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.5+6
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.6.1
  google_mlkit_face_detection: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: